# Copyright 2018 Alexandre Díaz <dev@redneboa.es>
# License AGPL-3.0 or later (http://www.gnu.org/licenses/agpl).

{
    "name": "PMS Channel Connector",
    "version": "14.0.1.0.0",
    "author": "Alexandre Díaz,Odoo Community Association (OCA)",
    "website": "https://github.com/hootel/hootel",
    "category": "pms/connector",
    "summary": "Pms Channel Connector Base",
    "depends": ["connector", "web_notify", "pms"],
    "external_dependencies": {"python": ["pypi-xmlrpc"]},
    "data": [
        "views/pms_channel_connector_issue_views.xml",
        "views/pms_room_type_availability_views.xml",
        "views/pms_reservation_views.xml",
        "views/pms_room_type_views.xml",
        "views/pms_folio_views.xml",
        "views/product_pricelist_views.xml",
        "views/product_pricelist_item_views.xml",
        "views/pms_room_type_restriction_views.xml",
        "views/pms_room_type_restriction_item_views.xml",
        "views/channel_pms_reservation_views.xml",
        "views/channel_pms_room_type_views.xml",
        "views/channel_pms_room_type_availability_views.xml",
        "views/channel_pms_room_type_restriction_views.xml",
        "views/channel_pms_room_type_restriction_item_views.xml",
        "views/channel_product_pricelist_views.xml",
        "views/channel_product_pricelist_item_views.xml",
        "views/channel_connector_backend_views.xml",
        "views/channel_ota_info_views.xml",
        "wizard/massive_changes.xml",
        "data/menus.xml",
        "data/cron_jobs.xml",
        "data/email_availability_watchdog.xml",
        "security/ir.model.access.csv",
        # 'security/wubook_security.xml',
        # 'views/res_config.xml'
    ],
    "test": [],
    "installable": True,
    "license": "AGPL-3",
}
